services:
  - type: web
    name: rizon-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: rizon
      - key: JWT_SECRET
        generateValue: true
      - key: RESEND_API_KEY
        sync: false
      - key: FROM_EMAIL
        value: onboarding@resend.dev
      - key: PORT
        value: 8080
